### PR TITLE
Added Rust segment

### PR DESCRIPTION
**Pull request by shingtaklam1324**
It shows the current default toolchain of rust, and only appears when `Cargo.toml` or `*.rs` is in a directory.

### CODE REVIEW

**Comment by shingtaklam1324** [comment]
Mhm... Git seems to have caught the `chmod -R` I did and seems to have shown a large number of changes...

**Comment by b-ryan** [comment]
Yeah you will have to make a new branch with your changes isolated. I don't want to merge in all those mode changes.

As for the segment itself, how necessary is checking for a Cargo.toml or *.rs file? What would happen if you did not have this functionality?

**Comment by shingtaklam1324** [comment]
That is for checking whether there are Rust related files, so that the segment is only displayed when it is relevent

**Comment by b-ryan** [comment]
So to clarify what I am asking:

- Is `rustc --version` specific to a given directory or is this segment going to be the same everywhere?
- If there weren't rust files in a given directory, would `rustc --version` cause an error?

I am trying to understand why exactly we would want to see if there are rust files. To compare this to other segments, like the php version segment, this segment just always shows the php version regardless of your directory.

**Comment by shingtaklam1324** [comment]
Rustc version is global, I just thought it may be better to have it hidden when rust files aren't present as it is quite long.

I'm not using Powerline shell at the moment so I can't really test this properly.

**Pull request closed without merging**
