### PR TITLE
Git-Segment: increased speed

### PR DESCRIPTION
**Pull request by knrdl**
increased speed of the git segment by searching for a .git-directory in current and all upper directories first. So if we aren't in a git project structure no git command is executed and a lot of loading-time saved

### CODE REVIEW

**Comment by b-ryan** [comment]
Thanks for the PR! Do you have some numbers on what sort of speed increase this gives?

**Comment by knrdl** [comment]
Thanks for your reply, here some test results __(measured on my machine)__:

Not in a git dir:
*  Without fix:
```
real	0m0.205s
user	0m0.160s
sys	0m0.036s
```

* With fix:
```
real	0m0.158s
user	0m0.138s
sys	0m0.036s
```

In a git dir:
*  Without fix:
```
real	0m0.202s
user	0m0.172s
sys	0m0.028s
```

* With fix:
```
real	0m0.205s
user	0m0.164s
sys	0m0.040s
```

**Comment by b-ryan** [comment]
Hey there - I have just gotten around to testing this. I am not seeing a *significant* speedup on my machine. I am using

```
time ( for _ in {1..1000}; do powerline-shell &>/dev/null ; done )
```

I am using a configuration that only has the git segment enabled. For me the segment was fastest as it currently is when in a git directory. I just realized I lost the data, but yeah - it was marginally faster as is. When not in a git directory, your change is faster, but not by a meaningful amount. Over 1000 runs it saved 4 seconds - so not much in the long run.

So aside from the change not seeming that meaningful, I have larger concerns about its correctness. For one, using `PWD` is not always accurate. If this change were to be incorporated the code should probably use the `cwd` property of the `Powerline` object that the git segment receives.

Secondly, the change won't work on Windows due to hard-coding the `/` separator. There would need to be some compatibility fixes.

Finally, I am just worried about whether this is the most accurate way to check for a git directory. For example perhaps there is a way to configure git to use a different directory name than `.git`? I don't know, personally, but I would not be surprised.

So all-in-all I lean towards not including this. Perhaps if I made a concerted effort to improve performance across the entire application it would be great. But as it stands it seems like a lot of work for minimal gains.

**Comment by knrdl** [comment]
Hi, you're right, I'll close the PR :)

I really like this project and python, but the python-base slows it to much down (python is maybe not the best choice for an interactive application) 
... so as a test I ported it to a minimalistic Go version which performs very well so far

https://github.com/knrdl/powerline-bash

**Comment by b-ryan** [comment]
Yeah I have come to the same conclusion - Python is not ideal here. Others have mentioned go as well. I have considered switching to Go and I will continue to do so.

**Pull request closed without merging**
