### PR TITLE
Add Python Version Segment

### PR DESCRIPTION
**Pull request by Blue-Dog-Archolite**

### CODE REVIEW

**Comment by b-ryan** [comment]
This change is so similar to several other version-checking segment that I think we need a better way to handle them. I am thinking maybe segments could start taking arguments and there should be something like an "stdout" segment. You could then use it in your config like:

```
"segments": [
  "hostname",
  {
    "type": "stdout",
    "options": {
      "command": ["python", "--version"]
    }
  }
]
```

What's going on here is that a segment in the config could be a map instead of just a string. When it is, it provides the "type" and "options" keys where "type" is the segment type and "options" are arbitrary options defined by that segment.

This is just a first take at what the configuration might look like. Thoughts @Blue-Dog-Archolite @jceaser @emansije

**Comment by Blue-Dog-Archolite** [comment]
I think this is a great idea. Would also allow for more complicated output such as a check for Pipfile, or Gemfile in order to show the detail for environments that you are currently in. 

I'll be happy to do some work to set this up. However, it would end up being towards the end of the week.

@jceaser @emansije

**Comment by emansije** [comment]
I love the flexibility of this approach. The README file could have a few examples on how to set those configurable segments.

**Comment by jceaser** [comment]
I agree with the idea of adding a configuration, no need to reinvent the wheel then.

**Comment by b-ryan** [comment]
#365

**Pull request closed without merging**
