### PR TITLE
Add git stash segment

### PR DESCRIPTION
**Pull request by apinkney97**
Up-to-date rework of #201, addressing issue #114.

This also refactors some common functions from the version control segments into `utils.py`.

### CODE REVIEW

**Comment by b-ryan** [comment]
Thanks for updating this. The diff shows a lot of changes - I'm not sure why. Perhaps you have to merge the latest master?

**Comment by apinkney97** [comment]
I think it is from the latest master (it's from ae33f7e7cf48583c7647a3481967aa0dfdb9909e at least).

This is broken into two commits:
- fc62b0f88835646b75682838dc88248214553892 touches a lot of files since it refactors out a lot of duplicated functions into `utils.py`
- 709c5ba215da0788acf1c1dcecb19f4f449c1b79 is the commit that adds the git stash segment, and uses the refactored functions

**Comment by uloco** [comment]
Still waiting for this like crazy... 😞

**Comment by apinkney97** [comment]
@b-ryan if you prefer I can rework this without fc62b0f (ie leave all the duplicated `get_PATH` and `x_subprocess_env` functions and either copy those functions from `segments.git` or import them) but my preference would be to leave it as it currently stands.

**Comment by b-ryan** [comment]
Sorry things have been crazy. Looking at this now.

**Comment by apinkney97** [comment]
Anecdotally it seems to render ok on my terminal in all fonts I've tried (10 or so different ones, powerline, non-powerline monospace, and proportional fonts). Possibly my terminal is being clever and pulling it from some font that does contain that glyph.

image

Seems to work even for totally crazy fonts that you'd never use in a terminal that don't support powerline:
image

Not quite sure whether I've done this right (I haven't really poked around inside fonts before) but I think this should list which fonts support a given unicode character:
```
$ for i in $(find /usr/share/fonts /usr/local/share/fonts -name "*.ttf"); do showttf $i 2>/dev/null | grep -i 'U+2398' && echo $i; done | grep "\.ttf" 
/usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf                              
/usr/share/fonts/truetype/freefont/FreeSerif.ttf                                        
/usr/share/fonts/truetype/freefont/FreeMono.ttf                                         
```

Admittedly it's not many (3 `.ttf` files out of 177) but I think those all shipped with the OS (Ubuntu 16.04).

Again, this is pretty anecdotal, but it seemed to work ok for people who commented on the old PR: https://github.com/b-ryan/powerline-shell/pull/201#issuecomment-158118239

**Comment by b-ryan** [comment]
Nice - thanks for looking into the fonts & making that change.

**Comment by uloco** [comment]
🎉 🎉 🎉 🎉 
Thank you guys :)))

**Pull request merged**
