### PR TITLE
"cwd": { "mode": "compact" }

### PR DESCRIPTION
**Pull request by mmariani**
I find this useful. It does not make a lot of sense together with "max_dir_size" but I did not want to change too much. Thanks for the package.

### CODE REVIEW

**Comment by b-ryan** [comment]
Thanks - this seems like a fine change to make. `max_dir_size` is not used consistently with this change, however. `max_dir_size` is supposed to represent the maximum size for each directory, but in this PR, `max_dir_size` shortens the entire thing. I would like to keep this consistent to avoid confusion. 

A little bit of refactoring could make this work nicely. I think if we just added this line right before your change it would work:

```python
names = [maybe_shorten_name(powerline, name) for name in names]
```

Then remove the call the `maybe_shorten_name` below. 

The last thing is that your code seems to me like it should call `powerline.append` directly and then exit the function, like done [here](https://github.com/mmariani/powerline-shell/blob/a7f17f2dc414e23a3bbcf4661f068d181ad2da30/powerline_shell/segments/cwd.py#L62-L63). The loop after your code is not really meant to be used outside of the context of adding individual directories one at a time. I wouldn't want to worry about what happens to "compact" mode if something inside that loops is changed.

**Comment by b-ryan** [comment]
Oh and thanks for the PR!

**Comment by b-ryan** [comment]
I just had another random thought, which is: I wonder if this should just be baked into "plain" mode rather than be a new "compact" mode. The only difference between "plain" and "compact" is that "plain" ignores those options - but someone can just leave them out if they don't want them.

**Comment by mmariani** [comment]
I think "max_dir_size" would still make sense to display only the last few directory names, but can live without.
I'll have a look at some experimental changes when I have some time, but it's better to open a new ticket

**Pull request closed without merging**
